env:
  browser: true
  es2021: true
extends:
  - "standard"
  - "plugin:react/recommended"
  - "prettier"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  semi:
    - "error"
    - "always"
  quotes:
    - "error"
    - "double"
